### ISSUE TITLE
bug: there is an error when integration actframework 

### ISSUE THREAD

**Issue by xkcoding** [zhangyd-c/JustAuth#27]
### 哪个平台？
系统：MacOS Mojave
JDK：jdk1.8.0_162
ActFramework：1.8.26.0
JustAuth：1.9.1

### 重现步骤
添加依赖，直接启动

### 报错信息
```java
Exception in thread "main" org.osgl.exception.UnexpectedMethodInvocationException: java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.osgl.exception.UnexpectedMethodInvocationException.triage(UnexpectedMethodInvocationException.java:44)
	at org.osgl.Lang.invokeStatic(Lang.java:8061)
	at act.Act.bootstrap(Act.java:1178)
	at act.Act.start(Act.java:688)
	at com.xkcoding.demo.AppEntry.main(AppEntry.java:24)
Caused by: java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(ClassLoader.java)
	at java.lang.ClassLoader._jr$defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:42016)
	at act.boot.BootstrapClassLoader.defineClassX(BootstrapClassLoader.java:96)
	at act.boot.BootstrapClassLoader.defineClass(BootstrapClassLoader.java:104)
	at act.boot.app.FullStackAppBootstrapClassLoader.loadActClass(FullStackAppBootstrapClassLoader.java:411)
	at act.boot.app.FullStackAppBootstrapClassLoader.loadClass(FullStackAppBootstrapClassLoader.java:375)
	at act.boot.app.FullStackAppBootstrapClassLoader.pluginClasses(FullStackAppBootstrapClassLoader.java:110)
	at act.Act.pluginClasses(Act.java:265)
	at act.plugin.PluginScanner.scan(PluginScanner.java:45)
	at act.Act.loadPlugins(Act.java:993)
	at act.Act.startup(Act.java:330)
	at act.Act.startup(Act.java:1272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45009)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45012)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Lang.invokeStatic(Lang.java:8059)
	... 3 more
```

**Comment by xkcoding** [comment]
因为 ActFramework 启动会去检查 是否存在 JDK 1.9 编译出来的文件，导致报错。

此错误是因为 JustAuth 里引入了 lombok 依赖导致，因此 JustAuth 1.9.1 及以前的版本需要在 pom 里降低 lombok 依赖，即可解决此问题。

```xml
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.16.0</version>
</dependency>
```
